### PR TITLE
initialize correct curves when signing without an instance

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
Addresses https://github.com/CityOfZion/neo-python-core/issues/176

**How did you solve this problem?**
Now the code initializes the correct curve parameters even if a `CryptoInstance` is not in use.

**How did you make sure your solution works?**
Wrote a test based on the code from https://github.com/CityOfZion/neo-python-core/issues/176
and `make test`

**Did you add any tests?**
Yes

**Did you run `make lint` and `make coverage`?**
Yes

**Are there any special changes in the code that we should be aware of?**
No

**NOTE:** I did search for other places where a private key is input and found none that are in use.

### CODE REVIEW

**Review by ixje — CHANGES_REQUESTED** [review]
These tests don't work properly. If I comment out 
```
Crypto.SetupSignatureCurve()
```
then all tests still pass which shouldn't happen. fyi; Ideally you start with writing tests and make sure you have tests that fail without the fix. Then apply the fix and the test should pass. That way you can avoid these scenarios.

**Comment by jseagrave21** [comment]
Thank you! I will keep working.

**Comment by jseagrave21** [comment]
@ixje okay the tests are valid now. I am not sure what happened with my last rebasing but I didn't change anything with the initial commit. I made the changes in the "update..." commit. I rebased to clarify my new test names. Hopefully they are clear.

**Review by ixje — APPROVED** [review]

**Comment by ixje** [comment]
`setUp` is called before every test case (whereas `setupClass` is called once for the whole TestCase class). This means `tearDown` didn't add anything

**Comment by ixje** [comment]
100 points seagrave

**Comment by jseagrave21** [comment]
> `setUp` is called before every test case (whereas `setupClass` is called once for the whole TestCase class). This means `tearDown` didn't add anything

@ixje thank you for clarifying! I misunderstood the explanation when I was researching the functions.

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/d5ae4a22ffe49912a2a3dc698d39ac63a8fcf2cef63ae136850d039c312591d8

**Pull request merged**
