### PR TITLE
according to C#, BigInteger(0) is b'\x00'

### PR DESCRIPTION
**Pull request by igormcoelho**
**What current issue(s) does this address, or what feature is it adding?**
I solves issue #49 
**How did you solve this problem?**
I used Eco platform (neocompiler.io) to test both networks simultaneously (Python and C#)
**How did you make sure your solution works?**
I also tested locally.
**Did you add any tests?**
I tested locally.
**Did you run `make lint` and `make coverage`?**
No.
**Are there any special changes in the code that we should be aware of?**
No.

### CODE REVIEW

**Comment by metachris** [comment]
Looks good. Could you please add a test?

**Comment by igormcoelho** [comment]
Hi Chris, unfortunately I'm not an expert in python, and have never dealt with tests before...
So, this means it will take some time, if you guys want to wait, it's up to you.

**Comment by metachris** [comment]
Thanks, should be fine :) Looking to get some final feedback about possible unexpected consequences @localhuman ?

**Comment by igormcoelho** [comment]
Yeah, I agree Chris that this may become some kind of bomb... I dont have any idea of the consequences hahaha. But I know for sure, the sooner this is included, the better. Thanks

**Comment by igormcoelho** [comment]
Thanks for the attention and congratulations for the good work.

**Pull request merged**
